# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer: {updated: HuggingFaceH4/ultrafeedback_binarized, original: HuggingFaceH4/ultrafeedback_binarized} # train & test
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
alpha: 0.0001
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: COPO-Llama-3-8B-Instruct
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: data/COPO-Llama-3-8B-Instruct
per_device_train_batch_size: 1           
per_device_eval_batch_size: 1          
push_to_hub: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 200
save_total_limit: 1
seed: 42
warmup_ratio: 0.1